definitions:
  models.CreateUserResponse:
    properties:
      id:
        type: integer
      success:
        type: boolean
    type: object
  models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /create-user:
    post:
      consumes:
      - application/json
      description: Accepts a JSON payload to create a new user and returns the new
        user ID
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created user ID
          schema:
            $ref: '#/definitions/models.CreateUserResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a new user
      tags:
      - users
  /users:
    get:
      description: Returns a list of all users (JWT-protected)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all users
      tags:
      - users
swagger: "2.0"
