definitions:
  models.ChangePasswordRequest:
    properties:
      new_password:
        type: string
      old_password:
        type: string
      user_id:
        type: integer
    type: object
  models.ChangePasswordResponse:
    properties:
      message:
        type: string
    type: object
  models.Claims:
    properties:
      exp:
        type: number
      user_id:
        type: integer
      username:
        type: string
    type: object
  models.ConversationInfo:
    properties:
      conversation_id:
        type: integer
      image_profile:
        $ref: '#/definitions/models.NullableString'
      last_message_at:
        type: string
      last_message_content:
        type: string
      user_id:
        type: integer
    type: object
  models.CreateUserPayload:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  models.CreateUserResponse:
    properties:
      id:
        type: integer
      success:
        type: boolean
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.GetConversationsResponse:
    properties:
      conversations:
        items:
          $ref: '#/definitions/models.ConversationInfo'
        type: array
      count:
        type: integer
      limit:
        type: integer
      offset:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  models.GetMessagesResponse:
    properties:
      count:
        type: integer
      limit:
        type: integer
      messages:
        items:
          $ref: '#/definitions/models.Message'
        type: array
      offset:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  models.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.LoginResponse:
    properties:
      id:
        type: integer
      token:
        type: string
    type: object
  models.Message:
    properties:
      content:
        type: string
      conversation_id:
        description: Fk to the conversation
        type: integer
      id:
        description: Pk of the message
        type: integer
      receiverID:
        type: integer
      senderID:
        type: integer
      sentAt:
        type: string
    type: object
  models.MessageResponseSucess:
    properties:
      message:
        type: string
    type: object
  models.NullableString:
    properties:
      string:
        type: string
      valid:
        type: boolean
    type: object
  models.SendMessageRequest:
    properties:
      content:
        type: string
      receiver_id:
        type: integer
    type: object
  models.TokenValidationResponse:
    properties:
      claims:
        $ref: '#/definitions/models.Claims'
      message:
        type: string
    type: object
  models.UserList:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  models.UserSearch:
    properties:
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: This is a Messaging app backend.
  title: Messenger
  version: "1.0"
paths:
  /change-password:
    post:
      consumes:
      - application/json
      description: Accepts a JSON payload to change the user's password
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password changed successfully
          schema:
            $ref: '#/definitions/models.ChangePasswordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Change user password
      tags:
      - Users
  /conversations:
    get:
      consumes:
      - application/json
      description: Get conversations for a user
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Conversations retrieved successfully
          schema:
            $ref: '#/definitions/models.GetConversationsResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get conversations
      tags:
      - Messages
  /create-user:
    post:
      consumes:
      - application/json
      description: Accepts a JSON payload to create a new user and returns the new
        user ID
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created user ID
          schema:
            $ref: '#/definitions/models.CreateUserResponse'
      summary: Create a new user
      tags:
      - Users
  /login:
    post:
      consumes:
      - application/json
      description: Accepts a JSON payload to log in the user and returns a JWT token
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token and user ID
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: User login
      tags:
      - Users
  /messages:
    get:
      consumes:
      - application/json
      description: Get messages between two users
      parameters:
      - description: Receiver ID
        in: query
        name: receiver_id
        required: true
        type: integer
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Messages retrieved successfully
          schema:
            $ref: '#/definitions/models.GetMessagesResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get messages
      tags:
      - Messages
  /search-users:
    get:
      consumes:
      - application/json
      description: Searches for users by username
      parameters:
      - description: Partial username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of users
          schema:
            items:
              $ref: '#/definitions/models.UserSearch'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      - Bearer: []
      summary: Search users by username
      tags:
      - Users
  /send-message:
    post:
      consumes:
      - application/json
      description: Send a message from one user to another
      parameters:
      - description: Message content
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.SendMessageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Message sent successfully
          schema:
            $ref: '#/definitions/models.MessageResponseSucess'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Send a message
      tags:
      - Messages
  /users:
    get:
      description: Returns a list of all users (JWT-protected)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserList'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all users
      tags:
      - Users
  /validate-token:
    get:
      consumes:
      - application/json
      description: Validates the JWT token and checks its expiration
      parameters:
      - description: JWT token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Token is valid
          schema:
            $ref: '#/definitions/models.TokenValidationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      - Bearer: []
      summary: Validate JWT token
      tags:
      - Users
  /ws-send:
    get:
      description: Connect to this endpoint via WebSocket to send/receive messages
      parameters:
      - description: "\tBearer <token>"
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "101":
          description: Switching Protocols
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: WebSocket chat
      tags:
      - WS Messages
securityDefinitions:
  ApiKeyAuth:
    description: 'Enter JWT token as: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
